import {
  boolean,
  index,
  integer,
  pgTable,
  text,
  timestamp,
} from 'drizzle-orm/pg-core'

export const JobsTable = pgTable(
  'jobs',
  {
    jobId: text('job_id').primaryKey(),
    angebotstitel: text('angebotstitel').notNull(),
    kurzbeschreibung: text('kurzbeschreibung').notNull(),
    firma: text('firma').notNull(),
    emailAnsprechpartner: text('email_ansprechpartner').notNull(),
    freigabedatum: timestamp('freigabedatum', { withTimezone: false }).notNull(),
    arbeitsort: text('arbeitsort').notNull(),
    anzeigeText: text('anzeige_text').notNull(),
    country: text('country').notNull(),
    einleitungTitel: text('einleitung_titel'),
    einleitungText: text('einleitung_text'),
    aufgabenTitel: text('aufgaben_titel'),
    aufgabenText: text('aufgaben_text'),
    erwartungenTitel: text('erwartungen_titel'),
    erwartungenText: text('erwartungen_text'),
    angebotTitel: text('angebot_titel'),
    angebotText: text('angebot_text'),
    kontaktTitel: text('kontakt_titel'),
    kontaktText: text('kontakt_text'),
    spracheDeutsch: boolean('sprache_deutsch').notNull(),
    spracheLand: boolean('sprache_land').notNull(),
    arbeitszeitMin: integer('arbeitszeit_min').notNull(),
    arbeitszeitMax: integer('arbeitszeit_max').notNull(),
    berufsfelder: text('berufsfelder').notNull(),
    fachbereiche: text('fachbereiche').notNull(),
    homeoffice: text('homeoffice').notNull(),
    jobtypen: text('jobtypen').notNull(),
  },
  t => [
    index('idx_job_search')
      .using(
        'bm25',
        t.jobId,
        t.angebotstitel,
        t.kurzbeschreibung,
        t.aufgabenText,
        t.erwartungenText,
        t.firma,
        t.arbeitsort,
        t.anzeigeText,
        t.fachbereiche,
        t.berufsfelder,
      )
      .with({ key_field: 'job_id' }),
  ],
)
