import type { ChatModel, ChatModelKey, Filters } from './types'

export const MODELS: ChatModel[] = [
  { key: 'gemini-2.0-flash', name: 'Gemini 2.0 Flash', company: 'Google' },
  { key: 'gemini-2.5-flash', name: 'Gemini 2.5 Flash', company: 'Google' },
  { key: 'gemini-2.5-pro', name: 'Gemini 2.5 Pro', company: 'Google' },
]
export const LIGHT_MODEL: ChatModelKey = MODELS[0]!.key

export const CHAT_CONFIG_COOKIE = 'chat-config'
export const DEFAULT_CHAT_CONFIG = { model: LIGHT_MODEL, search: false }

export const JOB_CATEGORIES = [
  'Abschlussarbeit',
  'Arbeitsstelle',
  'Ausbildung',
  'Berufseinstieg nach dem Studium',
  'Berufserfahrene',
  'DoktorandInnen',
  'Duales Studium',
  'MitgründerIn gesucht',
  'Nebenjob (fachfremd)',
  'Praktikum',
  'Traineeprogramm',
  'Werkstudierendenstelle und HiWi-Stellen',
]

export const JOB_TYPES = [
  'Festanstellung',
  'Befristet',
  'Freie Mitarbeit',
  'Minijob',
]

export const JOB_FIELDS = [
  'Agrartechnik',
  'Agrarwirtschaft, Landwirtschaft',
  'Banken, Finanzdienstleister, Versicherungen, Immobilien',
  'Bau, Vermessung, Gebäudetechnik und Architektur',
  'Big Data, Data Science, Business Intelligence, Wirtschaftsinformatik',
  'Bildungswesen, Lehrtätigkeit, Schule, Coaching, Training',
  'Bioingenieurw., Biotechnologie, Bioinformatik',
  'Chemie, Pharma, Biologie',
  'Datenbankentwicklung',
  'Druck, Medienproduktion',
  'Einkauf, Materialwirtschaft, Logistik, SCM, Qualitätswesen',
  'Energietechnik, Elektrotechnik, Energieerzeugung, Automatisierungstechnik',
  'Ernährung',
  'Erneuerbare Energien, nachwachsende Rohstoffe',
  'Erwachsenenbildung',
  'Film, Funk, Fernsehen',
  'Finanzen, Controlling, Buchhaltung, Finance',
  'Forschende und Lehrende, Promotion, HiWi, PostDoc',
  'Forstwirtschaft, Waldwirtschaft, Holzwirtschaft',
  'Fotografie',
  'Gastronomie, Hotel, Tourismus',
  'Gebäudetechnik, Versorgungstechnik, Sicherheitstechnik',
  'Geburtshilfe',
  'Geoinformatik',
  'Geschlechtersensible Soziale Arbeit',
  'Gesundheitshilfen, einschließlich Suchthilfe',
  'Grafik, Design, Mediendesign, Webdesign, Multimedia',
  'Hardwareentwicklung',
  'IT Beratung, IT Consulting, IT Vertrieb',
  'IT Projektmanagement, IT Leitung, IT Architektur',
  'IT Sicherheit',
  'IT Support, Helpdesk',
  'IT Testing',
  'IT und Telekommunikation, IT Beratung, IT Vertrieb, Wirtschaftsinformatik',
  'Jugendarbeit, Jugendsozialarbeit',
  'Jugendhilfe, Familienhilfe',
  'Kindergarten, Schule',
  'Klimawandel, Naturschutz, Umweltplanung',
  'Kosmetik, Körperpflege, Wellness',
  'Kunst und Kultur',
  'Labor, Forschung und Entwicklung',
  'Landschaftsarchitektur, Gartenbau',
  'Lebensmitteltechnologie, Brautechnologie, Getränketechnologie',
  'Lebensmittelwirtschaft',
  'Management und Beratung, Consulting',
  'Marketing, Werbung, Kommunikation, PR, Online Marketing, Eventmanagement',
  'Maschinenbau, Fahrzeugtechnik, Verkehrstechnik, Agrartechnik',
  'Materials Engineering, Werkstofftechnik, Materialwissenschaft',
  'Mathematik, Statistik',
  'Mechatronik, Feinwerktechnik, Robotik',
  'Medieninformatik, Geoinformatik, Bioinformatik',
  'Medizin- und Rehatechnik',
  'Medizin, Zahnmedizin',
  'Messe- und Veranstaltung',
  'Mode',
  'Museen, Restaurierung, Denkmalschutz',
  'Öffentlicher Dienst, Verwaltung, Behörden',
  'Personalwesen, HR, Recruiting',
  'Pflege, Therapie',
  'Pharmazie',
  'Physik',
  'Produktion, Fertigung, Qualitätswesen',
  'Psychologie',
  'Rechtswesen, Steuerwesen, Wirtschaftsprüfung, Steuerberatung',
  'Regionalmanagement',
  'Resozialisierung',
  'Softwareentwicklung, Programmierung',
  'Sonstige',
  'Sonstiges',
  'Soziale Arbeit im Bereich Migration',
  'Soziale Arbeit mit Menschen mit Behinderung und psychischer Erkrankung',
  'Soziale Arbeit mit und für ältere Menschen',
  'Sport und Bewegung',
  'Systemadministration, Netzwerkadministration',
  'Techn. Management, Projektplanung, Technischer Vertrieb',
  'Technische Entwicklung, Konstruktion, CAD',
  'Technische Traineeprogramme',
  'Tiergesundheit, Tiermedizin',
  'Umweltingenieurwesen',
  'Ver- und Entsorgung, Transport',
  'Verfahrenstechnik, Chemieingenieurwesen',
  'Verlagswesen, Bibliothek, Archiv',
  'Vertrieb, Verkauf, Handel, Sales, E-Commerce',
  'Verwaltung, Assistenz, Organisation, Sekretariat',
  'Wasserwirtschaft, Wassertechnologie',
  'Webentwicklung',
  'Wirtschaftsingenieurwesen',
]

export const JOB_HOMEOFFICES = [
  '0% Homeoffice',
  '0-49% Homeoffice',
  '50-100% Homeoffice',
  '100% Homeoffice',
]

export const JOB_WORKINGTIMES = {
  min: 0,
  max: 60,
}

export const DEFAULT_FILTER: Filters = {
  search: '',
  categories: [],
  types: [],
  fields: [],
  homeoffices: [],
  workingtimes: [JOB_WORKINGTIMES.min, JOB_WORKINGTIMES.max],
}

export const JOB_SEARCH_TARGET_COLUMNS = [
  'title',
  'company',
  'location',
  'fields',
  'short_description',
  'intro_text',
  'tasks_text',
  'expectations_text',
  'offer_text',
] as const
