import type { ChatModel, ChatModelKey } from './types'

export const MODELS: ChatModel[] = [
  { key: 'gemini-2.0-flash', name: 'Gemini 2.0 Flash', company: 'Google' },
  { key: 'gemini-2.5-flash', name: 'Gemini 2.5 Flash', company: 'Google' },
  { key: 'gemini-2.5-pro', name: 'Gemini 2.5 Pro', company: 'Google' },
]
export const LIGHT_MODEL: ChatModelKey = MODELS[0]!.key

export const CHAT_CONFIG_COOKIE = 'chat-config'
export const DEFAULT_CHAT_CONFIG = { model: LIGHT_MODEL, search: false }

export const JOB_TYPES = [
  'Abschlussarbeit',
  'Arbeitsstelle',
  'Ausbildung',
  'Berufseinstieg nach dem Studium',
  'Berufserfahrene',
  'DoktorandInnen',
  'Duales Studium',
  'MitgründerIn gesucht',
  'Nebenjob (fachfremd)',
  'Praktikum',
  'Traineeprogramm',
  'Werkstudierendenstelle und HiWi-Stellen',
]

export const JOB_FIELDS = [
  'Agrartechnik',
  'Agrarwirtschaft, Landwirtschaft',
  'Banken, Finanzdienstleister, Versicherungen, Immobilien',
  'Bau, Vermessung, Gebäudetechnik und Architektur',
  'Big Data, Data Science, Business Intelligence, Wirtschaftsinformatik',
  'Bildungswesen, Lehrtätigkeit, Schule, Coaching, Training',
  'Bioingenieurw., Biotechnologie, Bioinformatik',
  'Chemie, Pharma, Biologie',
  'Datenbankentwicklung',
  'Druck, Medienproduktion',
  'Einkauf, Materialwirtschaft, Logistik, SCM, Qualitätswesen',
  'Energietechnik, Elektrotechnik, Energieerzeugung, Automatisierungstechnik',
  'Ernährung',
  'Erneuerbare Energien, nachwachsende Rohstoffe',
  'Erwachsenenbildung',
  'Film, Funk, Fernsehen',
  'Finanzen, Controlling, Buchhaltung, Finance',
  'Forschende und Lehrende, Promotion, HiWi, PostDoc',
  'Forstwirtschaft, Waldwirtschaft, Holzwirtschaft',
  'Fotografie',
  'Gastronomie, Hotel, Tourismus',
  'Gebäudetechnik, Versorgungstechnik, Sicherheitstechnik',
  'Geburtshilfe',
  'Geoinformatik',
  'Geschlechtersensible Soziale Arbeit',
  'Gesundheitshilfen, einschließlich Suchthilfe',
  'Grafik, Design, Mediendesign, Webdesign, Multimedia',
  'Hardwareentwicklung',
  'IT Beratung, IT Consulting, IT Vertrieb',
  'IT Projektmanagement, IT Leitung, IT Architektur',
  'IT Sicherheit',
  'IT Support, Helpdesk',
  'IT Testing',
  'IT und Telekommunikation, IT Beratung, IT Vertrieb, Wirtschaftsinformatik',
  'Jugendarbeit, Jugendsozialarbeit',
  'Jugendhilfe, Familienhilfe',
  'Kindergarten, Schule',
  'Klimawandel, Naturschutz, Umweltplanung',
  'Kosmetik, Körperpflege, Wellness',
  'Kunst und Kultur',
  'Labor, Forschung und Entwicklung',
  'Landschaftsarchitektur, Gartenbau',
  'Lebensmitteltechnologie, Brautechnologie, Getränketechnologie',
  'Lebensmittelwirtschaft',
  'Management und Beratung, Consulting',
  'Marketing, Werbung, Kommunikation, PR, Online Marketing, Eventmanagement',
  'Maschinenbau, Fahrzeugtechnik, Verkehrstechnik, Agrartechnik',
  'Materials Engineering, Werkstofftechnik, Materialwissenschaft',
  'Mathematik, Statistik',
  'Mechatronik, Feinwerktechnik, Robotik',
  'Medieninformatik, Geoinformatik, Bioinformatik',
  'Medizin- und Rehatechnik',
  'Medizin, Zahnmedizin',
  'Messe- und Veranstaltung',
  'Mode',
  'Museen, Restaurierung, Denkmalschutz',
  'Öffentlicher Dienst, Verwaltung, Behörden',
  'Personalwesen, HR, Recruiting',
  'Pflege, Therapie',
  'Pharmazie',
  'Physik',
  'Produktion, Fertigung, Qualitätswesen',
  'Psychologie',
  'Rechtswesen, Steuerwesen, Wirtschaftsprüfung, Steuerberatung',
  'Regionalmanagement',
  'Resozialisierung',
  'Softwareentwicklung, Programmierung',
  'Sonstige',
  'Sonstiges',
  'Soziale Arbeit im Bereich Migration',
  'Soziale Arbeit mit Menschen mit Behinderung und psychischer Erkrankung',
  'Soziale Arbeit mit und für ältere Menschen',
  'Sport und Bewegung',
  'Systemadministration, Netzwerkadministration',
  'Techn. Management, Projektplanung, Technischer Vertrieb',
  'Technische Entwicklung, Konstruktion, CAD',
  'Technische Traineeprogramme',
  'Tiergesundheit, Tiermedizin',
  'Umweltingenieurwesen',
  'Ver- und Entsorgung, Transport',
  'Verfahrenstechnik, Chemieingenieurwesen',
  'Verlagswesen, Bibliothek, Archiv',
  'Vertrieb, Verkauf, Handel, Sales, E-Commerce',
  'Verwaltung, Assistenz, Organisation, Sekretariat',
  'Wasserwirtschaft, Wassertechnologie',
  'Webentwicklung',
  'Wirtschaftsingenieurwesen',
]

export const JOB_DOMAINS = [
  'Agrarwirtschaft / Agrartechnik',
  'Angewandte Chemie',
  'Angewandte Geistes- und Naturwissenschaften',
  'Angewandte Gesundheits- und Sozialwissenschaften',
  'Angewandte Mathematik, Physik und Allgemeinwissenschaften',
  'Angewandte Natur- und Geisteswissenschaften',
  'Angewandte Natur- und Kulturwissenschaften',
  'Angewandte Naturwissenschaften',
  'Angewandte Naturwissenschaften und Mechatronik',
  'Angewandte Sozial- und Gesundheitswissenschaften',
  'Angewandte Sozialwissenschaften',
  'Architektur',
  'Architektur und Bauwesen',
  'Bauingenieurwesen',
  'Betriebswirtschaft',
  'Biotechnologie / Bioinformatik',
  'Brau- und Getränketechnologie',
  'Business School',
  'BWL-Dienstleistungsmanagement',
  'BWL-Digital Commerce Management',
  'BWL-Food Management',
  'BWL-Handel',
  'Design',
  'Elektro- und Informationstechnik',
  'Elektrotechnik',
  'Elektrotechnik Feinwerktechnik Informationstechnik',
  'Elektrotechnik und Informatik',
  'Elektrotechnik und Informationstechnik',
  'Ernährung und Versorgung',
  'Erneuerbare Energien / Nachwachsende Rohstoffe',
  'Fahrzeugtechnik, Flugzeugtechnik, Maschinenbau',
  'Forst- und Holzwirtschaft',
  'Gartenbau',
  'Geoinformation',
  'Gestaltung',
  'Gesundheitsmanagement',
  'Gesundheitswissenschaften',
  'Holztechnik und Bau',
  'Informatik',
  'Informatik und Mathematik',
  'Informationsmanagement',
  'Ingenieurwissenschaften',
  'Interdisziplinäre Studien',
  'Interdisziplinäre und innovative Wissenschaften',
  'Klimaschutz, Klimawandel',
  'Landschaftsarchitektur/ -bau',
  'Lebensmittelwirtschaft',
  'Maschinenbau',
  'Maschinenbau und Automobiltechnik',
  'Maschinenbau und Verfahrenstechnik',
  'Maschinenbau und Versorgungstechnik',
  'Maschinenbau/Umwelttechnik',
  'Medien',
  'MUC.DAI - Munich Center for Digital Sciences and AI',
  'Nachhaltige Infrastruktur',
  'Naturschutz / Umweltplanung',
  'Pflegemanagement',
  'Regionalmanagement',
  'Religionspädagogik',
  'School of Health',
  'Soziale Arbeit',
  'Soziale Arbeit und Gesundheit',
  'Sozialwesen',
  'Studienfakultät der Weiterbildung',
  'Studium Generale und Interdisziplinäre Studien',
  'Technik',
  'Technische Systeme, Prozesse und Kommunikation',
  'Tourismus',
  'Umweltsicherung / Wassertechnologie',
  'Verfahrenstechnik',
  'Weiden Business School',
  'Wein - Technologie - Management',
  'Werkstofftechnik',
  'Wirtschaft',
  'Wirtschaft und Recht',
  'Wirtschaftsinformatik',
  'Wirtschaftsingenieurwesen',
  'Wirtschaftsingenieurwesen und Gesundheit',
  'Wirtschaftswissenschaften',
]

export const JOB_HOMEOFFICES = [
  '0% Homeoffice',
  '0-49% Homeoffice',
  '50-100% Homeoffice',
  '100% Homeoffice',
]

export const JOB_WORKINGTIMES = {
  min: 0,
  max: 60,
}

export const JOB_SEARCH_TARGET_ORIGIN_COLUMNS = [
  'angebotstitel',
  'kurzbeschreibung',
  'aufgaben_text',
  'erwartungen_text',
  'firma',
  'arbeitsort',
  'anzeige_text',
  'fachbereiche',
  'berufsfelder',
] as const

export const JOB_SEARCH_TARGET_COLUMNS = [
  'angebotstitel',
  'kurzbeschreibung',
  'aufgabenText',
  'erwartungenText',
  'firma',
  'arbeitsort',
  'anzeigeText',
  'fachbereiche',
  'berufsfelder',
] as const
